DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS data_point;
DROP TABLE IF EXISTS news;
CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);
CREATE TABLE data_point (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  total INTEGER NOT NULL,
  sentiment REAL NOT NULL,
  point_date TIMESTAMP NOT NULL,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creator_id INTEGER NOT NULL,
  FOREIGN KEY (creator_id) REFERENCES user (id)
);
CREATE TABLE news (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  statement_date TIMESTAMP NOT NULL,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creator_id INTEGER NOT NULL,
  FOREIGN KEY (creator_id) REFERENCES user (id)
);
